### ISSUE TITLE
Pequeñas faltas de ortografía en la memoria

### ISSUE THREAD

**Issue by sambrista** [jesusdavidguti/ProyectoFinDeCurso#5]
> Las versiones de Bootstrrap hacen que determinados

Bootstrap

> Las queys que lancemos con JPA desde backend

Las querys (o puedes poner consultas) que lancemos...

>  de que algunas de las llamadas a la API no haya finalizado

"alguna de las llamadas a la API no haya finalizado" o "algunas de las llamadas a la API no hayan finalizado"

>  Es JPA y Spring los que, mediante anotaciones

Son JPA y Spring los que...

**Comment by jesusdavidguti** [comment]
Solventadas.
